import type {
    DocumentMetadataIconOptions,
    DocumentMetadataManifest,
    DocumentMetadataOpenGraphImage,
    DocumentMetadataOpenGraphImageOptions,
    DocumentMetadataOpenGraphOptions,
    DocumentMetadataStructuredData,
    DocumentMetadataStructuredDataValue,
    DocumentMetadataTwitterOptions,
    DocumentMetadataUpdateOptions,
    DocumentMetadataUrlValue
} from "./createDocumentMetadata";

/**
 * Schema.org SoftwareApplication options generated by createAppDocumentMetadata().
 */
export interface AppDocumentMetadataSoftwareApplicationOptions {
    /** Application name used in JSON-LD. Defaults to the app metadata title or name. */
    name?: string | null;
    /** Application description used in JSON-LD. Defaults to the app metadata description. */
    description?: string | null;
    /** Schema.org application category, such as "EducationalApplication". */
    applicationCategory?: string | null;
    /** Supported operating system, such as "Web". */
    operatingSystem?: string | null;
    /** Public application URL used in JSON-LD. Defaults to app url/canonical metadata. */
    url?: DocumentMetadataUrlValue | null;
    /** Public preview image URL used in JSON-LD. Defaults to the app social image URL. */
    image?: DocumentMetadataUrlValue | null;
    /** Additional JSON-LD fields merged into the generated SoftwareApplication object. */
    additionalData?: { readonly [key: string]: DocumentMetadataStructuredDataValue };
}

/**
 * Declarative public-app metadata accepted by createAppDocumentMetadata().
 */
export interface AppDocumentMetadataOptions extends Omit<
    DocumentMetadataUpdateOptions,
    "title" | "description" | "canonical" | "openGraph" | "twitter" | "structuredData"
> {
    /** Product, site, or application name used as the default title and social site name. */
    name: string;
    /** Browser document title. Defaults to name. Pass null only when removing a managed title. */
    title?: string | null;
    /** Meta description used by browsers, search engines, and generated social metadata. */
    description?: string | null;
    /** Public app URL used as the default canonical and shared URL. */
    url?: DocumentMetadataUrlValue | null;
    /** Canonical page URL. Defaults to url when url is provided. */
    canonical?: DocumentMetadataUrlValue | null;
    /** Open Graph site_name. Defaults to name. */
    siteName?: string | null;
    /** Shared preview image used by generated Open Graph, Twitter, and SoftwareApplication metadata. */
    image?: DocumentMetadataOpenGraphImage | null;
    /** Shared preview image alt text used by generated Twitter metadata. */
    imageAlt?: string | null;
    /** Open Graph overrides, null to remove managed tags, or false to skip generated Open Graph metadata. */
    openGraph?: DocumentMetadataOpenGraphOptions | null | false;
    /** Twitter/X card overrides, null to remove managed tags, or false to skip generated Twitter metadata. */
    twitter?: DocumentMetadataTwitterOptions | null | false;
    /** Custom JSON-LD, null to remove managed JSON-LD, or false to skip generated structured data. */
    structuredData?: DocumentMetadataStructuredData | null | false;
    /** Generates Schema.org SoftwareApplication JSON-LD when custom structuredData is not provided. */
    softwareApplication?: AppDocumentMetadataSoftwareApplicationOptions | null | false;
}

function getAppDocumentTitle(options: AppDocumentMetadataOptions): string | null {
    return "title" in options ? options.title ?? null : options.name;
}

function getAppDocumentDescription(options: AppDocumentMetadataOptions): string | null {
    return "description" in options ? options.description ?? null : null;
}

function getAppDocumentCanonical(
    options: AppDocumentMetadataOptions
): DocumentMetadataUrlValue | null | undefined {
    if ("canonical" in options) return options.canonical ?? null;

    return options.url;
}

function getAppDocumentSharedUrl(
    options: AppDocumentMetadataOptions,
    canonical: DocumentMetadataUrlValue | null | undefined
): DocumentMetadataUrlValue | null {
    if ("url" in options) return options.url ?? null;

    return canonical ?? null;
}

function stringifyAppMetadataUrl(value: DocumentMetadataUrlValue | null | undefined): string | null {
    if (value === null || value === undefined) return null;

    return value instanceof URL ? value.toString() : value;
}

function isOpenGraphImageOptions(
    image: DocumentMetadataOpenGraphImage | null | undefined
): image is DocumentMetadataOpenGraphImageOptions {
    return Boolean(image && typeof image === "object" && !(image instanceof URL) && "url" in image);
}

function getAppDocumentImageUrl(
    image: DocumentMetadataOpenGraphImage | null | undefined
): DocumentMetadataUrlValue | null {
    if (!image) return null;
    if (typeof image === "string" || image instanceof URL) return image;

    return image.url;
}

function getAppDocumentImageAlt(options: AppDocumentMetadataOptions): string | null {
    if ("imageAlt" in options) return options.imageAlt ?? null;

    return isOpenGraphImageOptions(options.image) ? options.image.alt ?? null : null;
}

function getAppDocumentSiteName(options: AppDocumentMetadataOptions): string | null {
    return "siteName" in options ? options.siteName ?? null : options.name;
}

function createAppOpenGraphMetadata(
    options: AppDocumentMetadataOptions,
    title: string | null,
    description: string | null,
    sharedUrl: DocumentMetadataUrlValue | null
): DocumentMetadataOpenGraphOptions | null | undefined {
    if (options.openGraph === false) return undefined;
    if (options.openGraph === null) return null;

    const openGraph: DocumentMetadataOpenGraphOptions = {
        type: "website"
    };
    const siteName = getAppDocumentSiteName(options);

    if (title !== null) openGraph.title = title;
    if (sharedUrl !== null) openGraph.url = sharedUrl;
    if (description !== null) openGraph.description = description;
    if (siteName !== null) openGraph.siteName = siteName;
    if ("image" in options) openGraph.image = options.image ?? null;

    return {
        ...openGraph,
        ...(options.openGraph ?? {})
    };
}

function createAppTwitterMetadata(
    options: AppDocumentMetadataOptions,
    title: string | null,
    description: string | null
): DocumentMetadataTwitterOptions | null | undefined {
    if (options.twitter === false) return undefined;
    if (options.twitter === null) return null;

    const twitter: DocumentMetadataTwitterOptions = {
        card: "summary"
    };
    const imageUrl = getAppDocumentImageUrl(options.image);
    const imageAlt = getAppDocumentImageAlt(options);

    if (title !== null) twitter.title = title;
    if (description !== null) twitter.description = description;
    if (imageUrl !== null) twitter.image = imageUrl;
    if (imageAlt !== null) twitter.imageAlt = imageAlt;

    return {
        ...twitter,
        ...(options.twitter ?? {})
    };
}

function createSoftwareApplicationStructuredData(
    options: AppDocumentMetadataOptions,
    title: string | null,
    description: string | null,
    sharedUrl: DocumentMetadataUrlValue | null
): DocumentMetadataStructuredData | undefined {
    const softwareApplication = options.softwareApplication;

    if (softwareApplication === false || softwareApplication === null || softwareApplication === undefined) return undefined;

    const data: { [key: string]: DocumentMetadataStructuredDataValue } = {
        "@context": "https://schema.org",
        "@type": "SoftwareApplication"
    };
    const name = "name" in softwareApplication
        ? softwareApplication.name ?? null
        : title ?? options.name;
    const resolvedDescription = "description" in softwareApplication
        ? softwareApplication.description ?? null
        : description;
    const resolvedUrl = "url" in softwareApplication
        ? softwareApplication.url ?? null
        : sharedUrl;
    const imageUrl = "image" in softwareApplication
        ? softwareApplication.image ?? null
        : getAppDocumentImageUrl(options.image);

    const applicationCategory = softwareApplication.applicationCategory ?? null;
    const operatingSystem = softwareApplication.operatingSystem ?? null;

    if (name !== null) data.name = name;
    if (resolvedDescription !== null) data.description = resolvedDescription;
    if (applicationCategory !== null) data.applicationCategory = applicationCategory;
    if (operatingSystem !== null) data.operatingSystem = operatingSystem;
    if (resolvedUrl !== null) data.url = stringifyAppMetadataUrl(resolvedUrl);
    if (imageUrl !== null) data.image = stringifyAppMetadataUrl(imageUrl);

    if (softwareApplication.additionalData) {
        Object.assign(data, softwareApplication.additionalData);
    }

    return data;
}

function createAppStructuredData(
    options: AppDocumentMetadataOptions,
    title: string | null,
    description: string | null,
    sharedUrl: DocumentMetadataUrlValue | null
): DocumentMetadataStructuredData | null | undefined {
    if ("structuredData" in options) {
        if (options.structuredData === false) return undefined;

        return options.structuredData ?? null;
    }

    return createSoftwareApplicationStructuredData(options, title, description, sharedUrl);
}

/**
 * Creates document metadata for public applications from one declarative app identity.
 */
export function createAppDocumentMetadata(
    options: AppDocumentMetadataOptions
): DocumentMetadataUpdateOptions {
    const title = getAppDocumentTitle(options);
    const description = getAppDocumentDescription(options);
    const canonical = getAppDocumentCanonical(options);
    const sharedUrl = getAppDocumentSharedUrl(options, canonical);
    const openGraph = createAppOpenGraphMetadata(options, title, description, sharedUrl);
    const twitter = createAppTwitterMetadata(options, title, description);
    const structuredData = createAppStructuredData(options, title, description, sharedUrl);
    const metadata: DocumentMetadataUpdateOptions = {
        title
    };

    if ("lang" in options) metadata.lang = options.lang ?? null;
    if ("description" in options) metadata.description = options.description ?? null;
    if ("viewport" in options) metadata.viewport = options.viewport ?? null;
    if ("themeColor" in options) metadata.themeColor = options.themeColor ?? null;
    if ("icons" in options) metadata.icons = options.icons ?? null;
    if (canonical !== undefined) metadata.canonical = canonical;
    if ("robots" in options) metadata.robots = options.robots ?? null;
    if ("manifest" in options) metadata.manifest = options.manifest ?? null;
    if (openGraph !== undefined) metadata.openGraph = openGraph;
    if (twitter !== undefined) metadata.twitter = twitter;
    if (structuredData !== undefined) metadata.structuredData = structuredData;

    return metadata;
}
